// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tictactoe.Model;

#nullable disable

namespace tictactoe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240818153611_DP-1")]
    partial class DP1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("tictactoe.Model.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Email");

                    b.ToTable("AppUser");
                });
#pragma warning restore 612, 618
        }
    }
}
